auth-filter:
  name: AuthFilter
  url: http://auth-cluster:8080/api/user/pass-id

cluster-ip:
  product: http://product-cluster:8080
  order: http://order-cluster:8080
  auth: http://auth-cluster:8080

spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: ${cluster-ip.order}
          predicates:
            - Path=/api/orders/**
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: order-webhook
          uri: ${cluster-ip.order}
          predicates:
            - Path=/api/payments/**

        - id: price-offer
          uri: ${cluster-ip.product}
          predicates:
            - Path=/api/price-offers/**
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: product-get-creator
          uri: ${cluster-ip.product}
          predicates:
            - Path=/api/products/common/creator
            - Method=GET
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: product-non-auth
          uri: ${cluster-ip.product}
          predicates:
            - Path=/api/products/**
            - Method=GET

        - id: product-auth-post
          uri: ${cluster-ip.product}
          predicates:
            - Path=/api/products/**
            - Method=POST
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: product-auth-patch
          uri: ${cluster-ip.product}
          predicates:
            - Path=/api/products/**
            - Method=PATCH
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: product-auth-delete
          uri: ${cluster-ip.product}
          predicates:
            - Path=/api/products/**
            - Method=DELETE
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: user-oauth
          uri: ${cluster-ip.auth}
          predicates:
            - Path=/api/oauth/**, /api/user/info, /api/user/sign-out, /api/user/profile-image, /api/user/password, /api/user/nickname, /api/user/address
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: user-with-auth
          uri: ${cluster-ip.auth}
          predicates:
            - Path=/api/user/sign-up, /api/user/sign-in, /api/user/refresh
       #- id: company-without-auth
       #- id: company-with-auth

      # cors settings
      globalcors:
        cors-configurations:
          "[/**]":
            allow-credentials: true
            allowed-origin-patterns:
              - "*"
            allowed-headers:
              - "*"
            exposed-headers:
              - "access-token"
              - "refresh-token"
            allowed-methods:
              - "*"
logging:
  level:
    org.springframework.cloud.gateway: info