auth-filter:
  name: AuthFilter
  url: http://auth-cluster:8080/api/auth/pass-id

cluster-ip:
  product: http://product-cluster:8080
  order: http://order-cluster:8080
  auth: http://auth-cluster:8080

spring:
  cloud:
    gateway:
      routes:
# ---------------- Order
        - id: order
          uri: ${cluster-ip.order}
          predicates:
            - Path=/api/orders/**
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: order-webhook
          uri: ${cluster-ip.order}
          predicates:
            - Path=/api/payments/**

        - id: price-offer
          uri: ${cluster-ip.product}
          predicates:
            - Path=/api/price-offers/**
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

# ------------------- Product
        - id: product-non-auth
          uri: ${cluster-ip.product}
          predicates:
            - Path=/api/products/**
            - Method=GET

        - id: product-auth-post
          uri: ${cluster-ip.product}
          predicates:
            - Path=/api/products/**
            - Method=POST
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: product-auth-patch
          uri: ${cluster-ip.product}
          predicates:
            - Path=/api/products/**
            - Method=PATCH
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: product-auth-delete
          uri: ${cluster-ip.product}
          predicates:
            - Path=/api/products/**
            - Method=DELETE
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}
# --------------------------------- Auth
        - id: auth-noAuth
          uri: ${cluster-ip.auth}
          predicates:
            - Path=/api/auth/email, /api/auth/sign-in, /api/auth/refresh

        - id: auth-auth
          uri: ${cluster-ip.auth}
          predicates:
            - Path=/api/auth/pwd, /api/auth/sign-out

        - id: user-oauth-noAuth
          uri: ${cluster-ip.auth}
          predicates:
            - Path=/oauth2/**, /login/**, /callback/**

        - id: user-oauth-auth
          uri: ${cluster-ip.auth}
          predicates:
            - Path=/api/oauth2/**
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: user-noAuth
          uri: ${cluster-ip.auth}
          predicates:
            - Path=/api/user/sign-up, /api/user/nickname

        - id: user-with-auth
          uri: ${cluster-ip.auth}
          predicates:
            - Path=/api/user/auth-info, /api/user/image
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

        - id: company-noAuth
          uri: ${cluster-ip.auth}
          predicates:
            - Path=/api/company/sign-up, /api/company/info/**, /api/company/infos

        - id: company-auth
          uri: ${cluster-ip.auth}
          predicates:
            - Path=/api/company/auth-info, /api/company/description, /api/company/short-description, /api/company/image
          filters:
            - name: ${auth-filter.name}
              args:
                authServerUrl: ${auth-filter.url}

# ------------------------- Chat
      # cors settings
      globalcors:
        cors-configurations:
          "[/**]":
            allow-credentials: true
            allowed-origin-patterns:
              - "*"
            allowed-headers:
              - "*"
            exposed-headers:
              - "access-token"
              - "refresh-token"
            allowed-methods:
              - "*"
logging:
  level:
    org.springframework.cloud.gateway: info