spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order-cluster:8080
          predicates:
            - Path=/api/orders/**
          filters:
            - name: AuthFilter
              args:
                authServerUrl: http://auth-cluster:8080/user/pass-id
        - id: order-webhook
          uri: http://order-cluster:8080
          predicates:
            - Path=/api/payments/**

        - id: price-offer
          uri: http://product-cluster:8080
          predicates:
            - Path=/api/price-offers/**
          filters:
            name: AuthFilter
            args:
              authServerUrl: http://auth-cluster:8080/user/pass-id
        - id: product-non-auth
          uri: http://product-cluster:8080
          predicates:
            - Path=/api/products/**
            - Method=GET
        - id: product-auth-post
          uri: http://product-cluster:8080
          predicates:
            - Path=/api/products/**
            - Method=POST
          filters:
            name: AuthFilter
            args:
              authServerUrl: http://auth-cluster:8080/user/pass-id
        - id: product-auth-patch
          uri: http://product-cluster:8080
          predicates:
            - Path=/api/products/**
            - Method=PATCH
          filters:
            name: AuthFilter
            args:
              authServerUrl: http://auth-cluster:8080/user/pass-id
        - id: product-auth-delete
          uri: http://product-cluster:8080
          predicates:
            - Path=/api/products/**
            - Method=DELETE
          filters:
            name: AuthFilter
            args:
              authServerUrl: http://auth-cluster:8080/user/pass-id
        - id: user-oauth
          uri: http://auth-cluster:8080
          predicates:
            - Path=/api/oauth/**, /api/user/info, /api/user/sign-out, /api/user/profile-image, /api/user/password, /api/user/nickname, /api/user/address
          filters:
            name: AuthFilter
            args:
              authServerUrl: http://auth-cluster:8080/user/pass-id

        - id: user-with-auth
          uri: http://auth-cluster:8080
          predicates:
            - Path=/api/user/sign-up, /api/user/sign-in, /api/user/refresh
       #- id: company-without-auth
       #- id: company-with-auth
      globalcors:
        cors-configurations:
          "[/**]":
            allow-credentials: true
            allowed-origins:
              - "*"
            allowed-headers:
              - Authorization
              - access-token
              - refresh-token
            allowed-methods:
              - GET
              - PATCH
              - POST
              - DELETE
logging:
  level:
    org.springframework.cloud.gateway: DEBUG